application: uni-collab
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "latest"

handlers:
- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/admin
  static_dir: django/contrib/admin/static/admin
  expiration: '0'

- url: /.*
  script: thinkster_django_angular_boilerplate.wsgi.application

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$

env_variables:
  DJANGO_SETTINGS_MODULE: 'thinkster_django_angular_boilerplate.settings'